### ISSUE TITLE
Libraries

### ISSUE THREAD

**Issue by Sebenzouz** [smhaller/dobot-m1#1]
Hello, I've just received my Dobot M1 and I would to test it using your demo. However, I don't find the differents libraries you use in your program : "rospy, trajectory_msgs.msg, etc..." . Can you share it to me please?
Thank's a lot

**Comment by smhaller** [comment]
These are standard ros packages. If you do a full installation (ros-melodic-desktop-full) - see   http://wiki.ros.org/melodic/Installation/Ubuntu - you should have all of them.

If you still have troubles running it - just re-open the Issue
